# .github/release.yml

changelog:
  categories:
    - title: Improves
      labels:
        - 'enhancement'
    - title: Bugs
      lables:
        - 'bug'      
      exclude:
        labels:
          - 'documentation'
    - title: Document Improvement
      lables:
        - 'documentation'
